[build]
  base = "/opt/build/repo"
  command = "yarn build"
  publish = "/opt/build/repo/.next"

[build.environment]
  NODE_VERSION = "16.20.2"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]