[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "16.20.2"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]